#!/usr/bin/env python3
"""PDF Summary Tool — extract text from a PDF and print a structured summary.

Usage:
    python3 pdf_summary.py <path-to-pdf>

Output: three sections (Overview, Key Points, Limitations) with [Page X]
citations generated by an LLM via OpenRouter.
"""

import argparse
import os
import sys

import pdfplumber
from openai import OpenAI
from dotenv import load_dotenv


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

load_dotenv()

OPENROUTER_BASE = "https://openrouter.ai/api/v1"
MODEL = "openrouter/free"

# Safety ceiling for the extracted text sent to the LLM.  Free models
# typically have an 8K-token context window; ~24 000 chars of English prose
# is roughly 6K tokens, leaving room for the system prompt and the reply.
MAX_CHARS = 24_000

SYSTEM_PROMPT = """You are a precise document summariser.

Your task is to read text extracted from a PDF and produce a structured
summary with exactly three sections:

1. Overview — a concise 2–4 sentence summary of what the document is about.
2. Key Points — a bullet list of the most important findings or arguments.
   Every bullet MUST end with a [Page X] citation in brackets, e.g. [Page 3].
3. Limitations — 1–2 sentences noting what the document does NOT cover, or
   gaps in the extracted text (e.g. missing figures, tables, or sections).

Rules:
- Use ONLY information present in the provided text.
- Do NOT invent facts, references, or page numbers not found in the text.
- If the text is too fragmented to produce a meaningful summary, say so
  honestly in the Overview and keep the Key Points list short.
- Keep the total output under 500 words.
- Output ONLY the three sections — no preamble, no sign-off."""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def parse_page_range(range_str: str) -> tuple[int, int]:
    """Parse a 'START-END' page range string.

    Returns (start, end) as 1-indexed inclusive integers.

    Prints a friendly message and exits on malformed input.
    """
    if "-" not in range_str:
        print(
            f"Error: Invalid page range '{range_str}'. "
            f"Expected format: START-END (e.g. 1-5).",
            file=sys.stderr,
        )
        sys.exit(1)

    parts = range_str.split("-", 1)
    if len(parts) != 2 or not parts[0] or not parts[1]:
        print(
            f"Error: Invalid page range '{range_str}'. "
            f"Both START and END are required (e.g. 1-5).",
            file=sys.stderr,
        )
        sys.exit(1)

    try:
        start = int(parts[0].strip())
        end = int(parts[1].strip())
    except ValueError:
        print(
            f"Error: Page numbers must be integers, got '{range_str}'.",
            file=sys.stderr,
        )
        sys.exit(1)

    if start < 1 or end < 1:
        print(
            f"Error: Page numbers must be >= 1, got '{range_str}'.",
            file=sys.stderr,
        )
        sys.exit(1)

    if start > end:
        print(
            f"Error: START ({start}) must be <= END ({end}).",
            file=sys.stderr,
        )
        sys.exit(1)

    return start, end


def load_api_key() -> str:
    """Load OPENROUTER_API_KEY from environment (set by python-dotenv)."""
    key = os.getenv("OPENROUTER_API_KEY", "").strip()
    if not key:
        print(
            "Error: OPENROUTER_API_KEY not found. "
            "Make sure your .env file contains OPENROUTER_API_KEY=your-key",
            file=sys.stderr,
        )
        sys.exit(1)
    return key


def extract_text(pdf_path: str,
                 page_start: int | None = None,
                 page_end: int | None = None) -> tuple[str, int]:
    """Extract text from *pdf_path* using pdfplumber.

    Args:
        pdf_path: Path to the PDF file.
        page_start: 1-indexed first page to extract (inclusive).  None = first page.
        page_end:   1-indexed last page to extract (inclusive).  None = last page.

    Returns:
        (text_block, total_pages)

        *text_block* joins non-empty pages delimited by [Page N] markers.
        Page numbers in citations always match the original PDF pagination.
        *total_pages* is the number of pages in the whole PDF.

    Raises:
        FileNotFoundError: *pdf_path* does not exist.
        pdfplumber.PDFSyntaxError: *pdf_path* is not a valid PDF.
    """
    try:
        doc = pdfplumber.open(pdf_path)
    except FileNotFoundError:
        raise
    except Exception as exc:
        print(
            f"Error: Could not open PDF file — {exc}",
            file=sys.stderr,
        )
        sys.exit(1)

    total_pages = len(doc.pages)

    # Resolve page range (1-indexed, inclusive)
    first = page_start if page_start is not None else 1
    last = page_end if page_end is not None else total_pages

    # Clamp to actual page count
    if first > total_pages:
        print(
            f"Error: START page ({first}) exceeds total pages ({total_pages}).",
            file=sys.stderr,
        )
        doc.close()
        sys.exit(1)
    last = min(last, total_pages)

    pages_text: list[str] = []
    for i in range(first - 1, last):
        page = doc.pages[i]
        page_num = i + 1  # original PDF page number
        try:
            text = page.extract_text()
        except Exception:
            text = None
        if text and text.strip():
            pages_text.append(f"[Page {page_num}]\n{text.strip()}")

    doc.close()

    return "\n\n".join(pages_text), total_pages


def build_user_message(text_block: str, total_pages: int, truncated: bool = False) -> str:
    """Construct the user prompt containing the extracted text."""
    truncation_note = ""
    if truncated:
        truncation_note = (
            "NOTE: The PDF text was too long and has been truncated to fit "
            "the model's context window. Some pages or sections may be missing. "
            "Please mention this truncation in the Limitations section.\n\n"
        )
    return (
        f"The PDF has {total_pages} page(s). "
        f"Below is the extracted text:\n\n"
        f"{truncation_note}"
        f"{text_block}\n\n"
        f"Please produce the three-section summary now."
    )


def call_openrouter(api_key: str, user_message: str) -> str:
    """Send the prompt to OpenRouter and return the assistant's reply."""
    client = OpenAI(base_url=OPENROUTER_BASE, api_key=api_key)

    try:
        response = client.chat.completions.create(
            model=MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_message},
            ],
            temperature=0.3,
        )
    except Exception as exc:
        msg = str(exc).lower()
        if "context length" in msg or "too long" in msg or "maximum context" in msg:
            print(
                "Error: The extracted text is too long for the model's context "
                "window. Try running again with a smaller --max-chars value, "
                "e.g.  python3 pdf_summary.py --max-chars 12000 <file.pdf>",
                file=sys.stderr,
            )
            sys.exit(1)
        print(f"Error: OpenRouter API call failed — {exc}", file=sys.stderr)
        sys.exit(1)

    try:
        return response.choices[0].message.content or ""
    except (AttributeError, IndexError, TypeError):
        print(
            "Error: Unexpected response format from OpenRouter API.",
            file=sys.stderr,
        )
        sys.exit(1)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    # 1. Parse arguments
    parser = argparse.ArgumentParser(
        description="Summarise a PDF file using an LLM via OpenRouter."
    )
    parser.add_argument(
        "pdf_path",
        help="Path to the PDF file to summarise",
    )
    parser.add_argument(
        "--max-chars",
        type=int,
        default=MAX_CHARS,
        help=(
            f"Maximum characters to send to the LLM "
            f"(default: {MAX_CHARS}, roughly 6K tokens). "
            f"Text beyond this limit is truncated with a warning."
        ),
    )
    parser.add_argument(
        "--pages",
        type=str,
        default=None,
        help=(
            "Page range to summarise (e.g. 1-5). "
            "Pages are 1-indexed and inclusive. "
            "Default: all pages."
        ),
    )
    args = parser.parse_args()

    # 2. Parse --pages range FIRST so malformed ranges are caught before
    #    we do any file I/O or API calls.
    page_start: int | None = None
    page_end: int | None = None
    if args.pages is not None:
        page_start, page_end = parse_page_range(args.pages)

    # 3. Check the file exists (friendly error, no traceback)
    if not os.path.isfile(args.pdf_path):
        print(
            f"Error: '{args.pdf_path}' does not exist or is not a file.",
            file=sys.stderr,
        )
        print(
            "Usage: python3 pdf_summary.py <path-to-pdf>",
            file=sys.stderr,
        )
        sys.exit(1)

    # 4. Sanity-check --max-chars
    if args.max_chars < 500:
        print(
            "Error: --max-chars must be at least 500.",
            file=sys.stderr,
        )
        sys.exit(1)

    # 5. Load API key (never printed)
    api_key = load_api_key()

    # 6. Extract text from PDF
    text_block, total_pages = extract_text(args.pdf_path, page_start, page_end)

    # 7. Guard: empty text (scanned PDF) → explain and exit, no LLM call
    if not text_block.strip():
        print(
            "Error: This PDF contains no extractable text. "
            "It may be a scanned image or a file with only embedded graphics. "
            "Cannot generate a summary.",
            file=sys.stderr,
        )
        sys.exit(1)

    # 8. Truncate if the extracted text exceeds the limit
    truncated = False
    if len(text_block) > args.max_chars:
        truncated = True
        original_len = len(text_block)
        text_block = text_block[:args.max_chars]
        # Cut cleanly at the last newline to avoid splitting a word / page marker
        last_nl = text_block.rfind("\n")
        if last_nl > args.max_chars // 2:
            text_block = text_block[:last_nl].rstrip()
        print(
            f"Warning: Extracted text ({original_len} chars) exceeds "
            f"--max-chars ({args.max_chars}). "
            f"Truncated to {len(text_block)} chars. "
            f"The summary may be incomplete.",
            file=sys.stderr,
        )

    # 9. Build prompt & call LLM
    user_message = build_user_message(text_block, total_pages, truncated=truncated)
    summary = call_openrouter(api_key, user_message)

    # 10. Print result (stdout only — keep it parseable)
    print(summary)


if __name__ == "__main__":
    main()
